In [3]:
import dhlab.nbtext as nb
import dhlab.module_update as mu
mu.update('mods_meta')
import mods_meta as mm

Updated file `D:\Documents\GitHub\Miscellaneous-Notebooks\reOCR\mods_meta.py`

In [31]:
nb.frame(nb.get_urn(metadata={'freetext':'Hamsun sult', 'limit':100}))

                0               1                     2     3
0   2008050604010    Hamsun, Knut                  Sult  1953
1   2008052004045    Hamsun, Tore     Det var i den tid  1959
2   2008071000094    Hamsun, Knut                  Sult  1996
3   2008112700038    Hamsun, Knut                  Sult  2001
4   2009011604050    Hamsun, Knut                  Sult  1998
5   2009031900017    Hamsun, Knut                  Sult  1990
6   2009032500001    Hamsun, Knut                  Sult  1990
7   2009051200010                                  Sult  1999
8   2011102508116    Hamsun, Knut                  Sult  1970
9   2012042508093    Hamsun, Knut                  Sult  1926
10  2013041506048    Vegge, Vally  Sult med variasjoner  2003
11  2014032506066    Hamsun, Knut                  Sult  1989
12  2014101508026    Hamsun, Knut                  Sult  1966
13  2014120208258    Hamsun, Knut                  Sult  1899
14  2015051929001    Hamsun, Knut                  Sult  1890
15  2015111007526    Hamsun, Knut                  Sult  1944
16  2016011906027    Hamsun, Knut                  Sult  2009
17  2016021609081  Sundvor, Yngve                  Sult  1998
18  2016040108083    Hamsun, Knut                  Sult  1999
19  2016093048045    Hamsun, Knut                  Sult  1989

In [16]:
import inspect

In [22]:
def make_corpus(author = None, title = None, subject = None, yearfrom = None, yearto = None):
    _,_,_, values = inspect.getargvalues(inspect.currentframe())
    print(values)

In [23]:
make_corpus()

{'author': None, 'title': None, 'subject': None, 'yearfrom': None, 'yearto': None}

In [10]:
corpus = mm.meta_natbib(yearfrom = 1880, yearto=1960, marctuples=[(100, 1, ' ', 'a', '%Hamsun%')])

In [12]:
nb.frame(mm.metadata([u[1] for u in corpus]))

,100-1- -a,245-1-0-a,245-1-0-b,260- - -c,653- - -a,lang,year
2007031901003,"Hamsun, Knut",Paa turne :,tre foredrag om litteratur,1960,"1800-tallet, essays, foredrag, hamsunknut, lit...",nob,1960
2007061301025,"Hamsun, Marie",Bygdebarn :,folk og fe på Langerud,1957,NaN,nob,1957
2008051600001,"Hamsun, Knut",Knut Hamsun som han var :,et utvalg av hans brev,1956,"litteratur, norsk",nob,1956
2008051604045,"Hamsun, Knut",Mysterier,NaN,1956,NaN,nob,1956
2008082710002,"Hamsun, Knut",Pan :,af Løjtnant Thomas Glahns Papirer,1894,NaN,nob,1894
2008091603014,"Hamsun, Knut",NaN,NaN,1915,NaN,nob,1915
2008091603015,"Hamsun, Knut",NaN,NaN,1915,NaN,nob,1915
2009051813003,"Hamsun, Knut",Stridende Liv :,Skildringer fra Vesten og Østen,1905,NaN,nob,1905
2011011106027,"Hamsun, Knut",Samlede Verker,NaN,1934,"litteratur, norsk",nob,1934
2011011706058,"Hamsun, Knut",Samlede Verker,NaN,1934,"litteratur, norsk",nob,1934
2011021406060,"Hamsun, Knut",Samlede Verker,NaN,1934,"litteratur, norsk",nob,1934
2011021506002,"Hamsun, Knut",Samlede Verker,NaN,1934,"litteratur, norsk",nob,1934
2011111108031,"Hamsun, Knut",Victoria,NaN,1951,NaN,nob,1951
2013012108029,"Hamsun, Knut",Samlede Verker,NaN,1934,"litteratur, norsk",nob,1934
2013073108082,"Hamsun, Knut",Børn av tiden,NaN,1931,NaN,nob,1931
2014021807151,"Hamsun, Knut",Dikte,NaN,1921,NaN,nob,1921
2014080408001,"Hamsun, Knut",NaN,NaN,1936,NaN,nob,1936
2016011129002,"Hamsun, Knut",Dronning Tamara :,Skuespil i tre Akter,1903,NaN,nob,1903
2016101148085,"Hamsun, Knut",Samlede Romaner og Fortællinger,NaN,&lt;1909&gt;,NaN,nob,1909
2016102848503,"Hamsun, Marie",Kultasateen alla,NaN,1960,NaN,mul,1960

In [26]:
mm??