In [51]:
import dhlab.nbtext as nb
import requests
import chart_studio.plotly as py
import plotly.figure_factory as ff
import plotly

In [100]:
def nb_search(
    term = '', creator = '', 
    number = 50, 
    page = 0, 
    mediatype = 'bøker', 
    lang = "nob",
    period = (18000101, 20401231)
):
    """Søk etter term og få ut json"""
    
    number = min(number, 50)
    
    filters = []
    aq = []
    

    params = {
        'page':page, 
        'size':number
    }
    
    if lang != '':
        aq.append('languages:{lang}'.format(lang = lang ))
    
    if creator != '':
        filters.append('creator:{c}'.format(c=creator))
    
    if mediatype != '':
        filters.append('mediatype:{mediatype}'.format(mediatype=mediatype))
    
    if period != ():
        filters.append('date:[{date_from} TO {date_to}]'.format(date_from = period[0], date_to = period[1]))
    
    if filters != []:
        params['filter'] = filters
    
    if aq != []:
        params['aq'] = aq
        
    if term != '':
        params['q'] = term
    
    r = requests.get("https://api.nb.no:443/catalog/v1/items", params = params)
    return r.json()

In [ ]:
def get_konks(phrase, author, period):
    import requests
    querystring = '"'+ phrase +'"' 
    query = {
        'q':querystring,
        'fragments': n,
        'fragSize':window
       
    }
    r = requests.get("https://api.nb.no/catalog/v1/items/{urn}/contentfragments".format(urn=urn), params = query)
    res = r.json()
    results = []
    try:
        for x in res['contentFragments']:
            pid = x['pageid']
            hit = x['text']
            splits = hit.split('<em>')
            s2 = splits[1].split('</em>')
            before = splits[0]
            word = s2[0]
            after = s2[1]
            results.append({'urn': urn, 'before': before, 'word':word, 'after':after})
    except:
        True
    return results

In [4]:
def word_frequencies(word_list):
    """ Find frequency of words global for digibok """
    params = {'words':word_list}
    r = requests.post("https://api.nb.no/ngram/word_frequencies", json=params)
    return dict(r.json())

In [7]:
nb.book_urn(words = ['samvittighet'])

[[2012060705064, 'Leer-Salvesen, Paul', 'Menneske og straff', 1991],
 [2011011806042, 'Janson, H.W.', 'Maleriets historie i bilder og tekst', 1958],
 [2014022006023, '', 'Ny teknologi i pleie og omsorg', 2009],
 [2012020808042, 'Trollope, Anthony', 'Søstrene i Allington', 1952],
 [2007041801056, 'Rönblom, H.-K.', 'Spionen Wennerström', 1965],
 [2013042506042, 'Juul, Jesper', 'Rom for familien', 2010],
 [2011032408020, 'Koksvik, Marion Berntzen', 'Aforismen er et enebarn', 2004],
 [2010070205102, 'Zwilgmeyer, Dikken', 'Annikken Prestgaren', 1953],
 [2013070408111, 'Garvang, Arne', 'helt tilfeldig forbrytelse', 2013],
 [2013080608138, 'Buckeridge, Anthony', 'Stompa på vingene', 1960],
 [2014070907241, 'Mathisen, Mona', 'Opp av sofaen', 2007],
 [2007032301004, 'Baraas, Olaf', 'Ved veis ende', 1964],
 [2014022708031, 'Staalesen, Gunnar', 'Blues for Amalie Jensen', 1994],
 [2014013008061, '', 'Når krigen raser', 2007],
 [2015043007536, 'McCullough, Colleen', 'Tornefuglene', 1978],
 [2013103005002, 'James, P.D.', 'Det svarte tårnet', 2007],
 [2013101408278, 'Kasparov, G.K.', 'Angrep i sjakk', 1986],
 [2008061204134, 'Westlie, Bjørn', 'I grenselandet', 1988],
 [2007041901029, 'Collins, Larry', 'Brenner Paris?', 1966],
 [2015021008057, '', 'Jakten på den fjerde sektor', 1999]]

In [84]:
words = nb.get_freq(2012060705064, top = 0)

In [85]:
tot = word_frequencies(list(words.keys()))

In [87]:
totals = nb.totals(500000)

In [89]:
t = nb.frame(totals)

In [97]:
t.iloc[100000:100020]

                 0
Fuglenes      8591
Duen          8591
verlieren     8590
skjænker      8590
fyaobe        8590
elevator      8590
Munich        8590
Bakte         8590
42,3          8590
1.1.3         8590
mustasjen     8589
husbands      8589
bytteforhold  8589
allefall      8589
Tapte         8589
Sydafrika     8589
røslig        8588
quinde        8588
overvældet    8588
håndverkeren  8588

In [27]:
words['hustrudræberne']

6

In [67]:
a = nb.frame(nb.frame(words)**1.02/nb.frame(tot), 'pmi').sort_values(by = 'pmi', ascending=False )

In [68]:
a.loc["straffen"]

pmi    0.004792
Name: straffen, dtype: float64

In [74]:
words['prevensjon']

42

In [30]:
nb.frame(nb.frame(words)/nb.frame(totals), 'pmi').sort_values(by = 'pmi', ascending=False ).head(50)

                       pmi
straffen          0.004231
soning            0.004043
gjerningsmannen   0.003488
strafferett       0.003401
forbrytelsen      0.003020
drapet            0.002951
Straffen          0.001955
Skylden           0.001767
Kants             0.001610
cella             0.001595
rettssalen        0.001582
drapsmann         0.001381
formildende       0.001325
prevensjon        0.001320
strafferettslig   0.001317
antropologi       0.001269
metafysisk        0.001247
offeret           0.001208
straff            0.001123
rettferdigheten   0.001112
rettferdighetens  0.001055
straffelov        0.001016
endatil           0.000970
skylden           0.000960
eksistensielle    0.000950
sikringen         0.000950
teologien         0.000913
straffer          0.000904
skyldfølelsen     0.000883
fengselet         0.000863
Straff            0.000844
drap              0.000840
lagmannsrettens   0.000827
dødsstraff        0.000812
Hallesby          0.000786
forbrytelse       0.000778
domfelte          0.000777
kriminaliteten    0.000777
Barth             0.000696
skyldige          0.000669
Helmut            0.000662
Immanuel          0.000652
juss              0.000639
forrang           0.000633
metafysikk        0.000627
strengeste        0.000623
Heidegger         0.000620
forsett           0.000619
forsoning         0.000607
Kant              0.000568

In [39]:
w = nb.totals(200000)

In [62]:
nb.book_urn(period=(1800, 1870), ddk = "839%")

[[2015011608061, '', 'Nordiske Oldskrifter', 1860],
 [2013052727006, 'Bruun, N.T.', 'Norge i September 1813', 1815],
 [2009102312001, '', 'Konge-speilet', 1848],
 [2013010208011, 'Kieler, Laura', 'Brands Døtre', 1869],
 [2009081403009, 'Collett, Camilla', 'Fortællinger', 1861],
 [2008112703011, 'Landstad, M.B.', 'Neslands kirke', 1852],
 [2006112300060, '', 'Sigmund Brestessøns Saga', 1861],
 [2007082703002, 'Zetlitz, Jens', "Jens Zetlitz's samlede Digte", 1825]]

In [65]:
import dhlab.module_update as mu
mu.update("illustration")

An error occured during download for illustration with error 404